"""bo sung cacbang phu cho ung vien

Revision ID: 02d0fbe7664e
Revises: 0667afc35fec
Create Date: 2026-04-04 21:31:10.024498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d0fbe7664e'
down_revision: Union[str, Sequence[str], None] = '0667afc35fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
