"""update candidate_profiles to v2 schema

Revision ID: 0667afc35fec
Revises: 160f51f1cf78
Create Date: 2026-04-03 15:57:54.500832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0667afc35fec'
down_revision: Union[str, Sequence[str], None] = '160f51f1cf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('skilltags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidate_profiles', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.alter_column('candidate_profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('candidate_profiles', 'years_of_experience')
    op.drop_column('candidate_profiles', 'skilltags')
    # ### end Alembic commands ###
