"""update

Revision ID: 0df075fe3f9e
Revises: d01f1daa4f3d
Create Date: 2026-04-29 11:37:32.329037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df075fe3f9e'
down_revision: Union[str, Sequence[str], None] = 'd01f1daa4f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. thêm cột mới
    op.add_column(
        'companies',
        sa.Column('is_vip_new', sa.Boolean(), nullable=False, server_default='false')
    )

    # 2. convert data
    op.execute("""
        UPDATE companies
        SET is_vip_new = CASE
            WHEN is_vip = 'ready' THEN true
            ELSE false
        END
    """)

    # 3. xoá cột cũ
    op.drop_column('companies', 'is_vip')

    # 4. rename lại
    op.alter_column('companies', 'is_vip_new', new_column_name='is_vip')

    # 5. xoá enum type
    op.execute("DROP TYPE vipenum")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'is_vip',
               existing_type=sa.Boolean(),
               type_=postgresql.ENUM('processing', 'ready', 'failed', name='vipenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'processing'::vipenum"))
    # ### end Alembic commands ###
