"""them truong nam kinh nghiem

Revision ID: 11c132c17c3a
Revises: c4b26e69fca3
Create Date: 2026-04-18 15:50:34.118894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c132c17c3a'
down_revision: Union[str, Sequence[str], None] = 'c4b26e69fca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'job_postings',
    sa.Column('years_of_experience', sa.Integer(), nullable=False, server_default="0")
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'years_of_experience')
    # ### end Alembic commands ###
