"""chinh lại relationship bang candidate profile

Revision ID: 14cbfa8f699b
Revises: 5fb84dbf811d
Create Date: 2026-04-10 11:04:20.964256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cbfa8f699b'
down_revision: Union[str, Sequence[str], None] = '5fb84dbf811d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
