"""update

Revision ID: 18e8b99eff97
Revises: 11c132c17c3a
Create Date: 2026-04-24 15:36:25.339480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e8b99eff97'
down_revision: Union[str, Sequence[str], None] = '11c132c17c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cv_upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'cv_uploads', ['cv_upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'cv_upload_id')
    # ### end Alembic commands ###
