"""Add benefits to job_postings

Revision ID: 1b572f22341a
Revises: c3de4a77b901
Create Date: 2026-06-14 16:38:08.270197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b572f22341a'
down_revision: Union[str, Sequence[str], None] = 'c3de4a77b901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_matching_jobs_candidate_id', table_name='ai_matching_jobs')
    op.drop_index('ix_ai_matching_jobs_cv_fingerprint', table_name='ai_matching_jobs')
    op.drop_index('ix_ai_matching_jobs_id', table_name='ai_matching_jobs')
    op.drop_index('ix_ai_matching_jobs_job_id', table_name='ai_matching_jobs')
    op.drop_index('uq_ai_matching_jobs_active_fingerprint', table_name='ai_matching_jobs', postgresql_where="(status = ANY (ARRAY['queued'::aimatchingjobstatusenum, 'processing'::aimatchingjobstatusenum]))")
    op.drop_table('ai_matching_jobs')
    op.drop_index('ix_parsed_cv_data_candidate_id', table_name='parsed_cv_data')
    op.drop_index('ix_parsed_cv_data_id', table_name='parsed_cv_data')
    op.drop_table('parsed_cv_data')
    op.drop_index('ix_subscription_plans_code', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_cycle', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_id', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('ix_payment_transactions_company_id', table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_created_by', table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_id', table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_plan_code', table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_status', table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_txn_ref', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_ai_matching_cache_candidate_id', table_name='ai_matching_cache')
    op.drop_index('ix_ai_matching_cache_cv_fingerprint', table_name='ai_matching_cache')
    op.drop_index('ix_ai_matching_cache_id', table_name='ai_matching_cache')
    op.drop_index('ix_ai_matching_cache_job_id', table_name='ai_matching_cache')
    op.drop_table('ai_matching_cache')
    op.add_column('job_postings', sa.Column('benefits', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'benefits')
    op.create_table('ai_matching_cache',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cv_fingerprint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name='ai_matching_cache_candidate_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], name='ai_matching_cache_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_matching_cache_pkey'),
    sa.UniqueConstraint('job_id', 'candidate_id', 'cv_fingerprint', name='uq_ai_matching_cache_job_candidate_fingerprint')
    )
    op.create_index('ix_ai_matching_cache_job_id', 'ai_matching_cache', ['job_id'], unique=False)
    op.create_index('ix_ai_matching_cache_id', 'ai_matching_cache', ['id'], unique=False)
    op.create_index('ix_ai_matching_cache_cv_fingerprint', 'ai_matching_cache', ['cv_fingerprint'], unique=False)
    op.create_index('ix_ai_matching_cache_candidate_id', 'ai_matching_cache', ['candidate_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('txn_ref', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('cycle', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_subunit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('response_code', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('bank_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('pay_date', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('raw_payload', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('paid_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vip_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('vip_expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('plan_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('vip_duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='payment_transactions_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='payment_transactions_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='payment_transactions_pkey')
    )
    op.create_index('ix_payment_transactions_txn_ref', 'payment_transactions', ['txn_ref'], unique=True)
    op.create_index('ix_payment_transactions_status', 'payment_transactions', ['status'], unique=False)
    op.create_index('ix_payment_transactions_plan_code', 'payment_transactions', ['plan_code'], unique=False)
    op.create_index('ix_payment_transactions_id', 'payment_transactions', ['id'], unique=False)
    op.create_index('ix_payment_transactions_created_by', 'payment_transactions', ['created_by'], unique=False)
    op.create_index('ix_payment_transactions_company_id', 'payment_transactions', ['company_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('cycle', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('price_vnd', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vip_duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='subscription_plans_pkey')
    )
    op.create_index('ix_subscription_plans_id', 'subscription_plans', ['id'], unique=False)
    op.create_index('ix_subscription_plans_cycle', 'subscription_plans', ['cycle'], unique=False)
    op.create_index('ix_subscription_plans_code', 'subscription_plans', ['code'], unique=True)
    op.create_table('parsed_cv_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('profile', 'uploaded_cv', name='cvtypeenum'), autoincrement=False, nullable=False),
    sa.Column('parse_status', postgresql.ENUM('pending', 'success', 'failed', name='parsestatusenum'), autoincrement=False, nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_text_snapshot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parser_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='parsed_cv_data_application_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name='parsed_cv_data_candidate_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='parsed_cv_data_pkey'),
    sa.UniqueConstraint('application_id', name='parsed_cv_data_application_id_key')
    )
    op.create_index('ix_parsed_cv_data_id', 'parsed_cv_data', ['id'], unique=False)
    op.create_index('ix_parsed_cv_data_candidate_id', 'parsed_cv_data', ['candidate_id'], unique=False)
    op.create_table('ai_matching_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cv_fingerprint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'processing', 'done', 'failed', 'dead', name='aimatchingjobstatusenum'), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_retry_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='ai_matching_jobs_application_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], name='ai_matching_jobs_candidate_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], name='ai_matching_jobs_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_matching_jobs_pkey'),
    sa.UniqueConstraint('application_id', name='ai_matching_jobs_application_id_key')
    )
    op.create_index('uq_ai_matching_jobs_active_fingerprint', 'ai_matching_jobs', ['job_id', 'candidate_id', 'cv_fingerprint'], unique=True, postgresql_where="(status = ANY (ARRAY['queued'::aimatchingjobstatusenum, 'processing'::aimatchingjobstatusenum]))")
    op.create_index('ix_ai_matching_jobs_job_id', 'ai_matching_jobs', ['job_id'], unique=False)
    op.create_index('ix_ai_matching_jobs_id', 'ai_matching_jobs', ['id'], unique=False)
    op.create_index('ix_ai_matching_jobs_cv_fingerprint', 'ai_matching_jobs', ['cv_fingerprint'], unique=False)
    op.create_index('ix_ai_matching_jobs_candidate_id', 'ai_matching_jobs', ['candidate_id'], unique=False)
    # ### end Alembic commands ###
