"""update

Revision ID: 1c60f7e6364c
Revises: 5fc40ce83de0
Create Date: 2026-04-27 01:57:45.446172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c60f7e6364c'
down_revision: Union[str, Sequence[str], None] = '5fc40ce83de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('saved_jobs_candidate_id_fkey'), 'saved_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'saved_jobs', 'candidate_profiles', ['candidate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('saved_jobs_candidate_id_fkey'), 'saved_jobs', 'applications', ['candidate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
