"""initial

Revision ID: 58b7c092244c
Revises: 
Create Date: 2026-06-23 16:15:49.623817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58b7c092244c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_alert_configs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_alert_configs_id'), 'ai_alert_configs', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', 'locked', name='companyverificationstatusenum'), nullable=True),
    sa.Column('is_vip', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vip_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('role_ai_quotas',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('daily_token_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_index(op.f('ix_role_ai_quotas_role'), 'role_ai_quotas', ['role'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cycle', sa.String(length=32), nullable=False),
    sa.Column('price_vnd', sa.Integer(), nullable=False),
    sa.Column('vip_duration_days', sa.Integer(), nullable=False),
    sa.Column('daily_ai_token_limit', sa.Integer(), server_default='10000', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=True)
    op.create_index(op.f('ix_subscription_plans_cycle'), 'subscription_plans', ['cycle'], unique=False)
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('candidate', 'hr_manager', 'admin', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'banned', 'deleted', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('skill_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_candidate_profiles_id'), 'candidate_profiles', ['id'], unique=False)
    op.create_table('company_documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), nullable=False),
    sa.Column('upload_by_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='documentstatus'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_documents_id'), 'company_documents', ['id'], unique=False)
    op.create_table('company_members',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_members_id'), 'company_members', ['id'], unique=False)
    op.create_table('company_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.BIGINT(), nullable=False),
    sa.Column('reviewed_by', sa.BIGINT(), nullable=True),
    sa.Column('license_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='verificationlogstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_verifications_id'), 'company_verifications', ['id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('benefits', sa.Text(), server_default='', nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_min', sa.BIGINT(), nullable=True),
    sa.Column('salary_max', sa.BIGINT(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('full_time', 'part_time', 'remote', name='jobtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'paused', 'closed', name='jobstatusenum'), nullable=False),
    sa.Column('locked_by_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('user_ai_quotas',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_ai_quota_date')
    )
    op.create_index(op.f('ix_user_ai_quotas_date'), 'user_ai_quotas', ['date'], unique=False)
    op.create_index(op.f('ix_user_ai_quotas_id'), 'user_ai_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_user_ai_quotas_user_id'), 'user_ai_quotas', ['user_id'], unique=False)
    op.create_table('candidate_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_certifications_id'), 'candidate_certifications', ['id'], unique=False)
    op.create_table('candidate_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_educations_id'), 'candidate_educations', ['id'], unique=False)
    op.create_table('candidate_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experiences_id'), 'candidate_experiences', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('job_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('company_follows',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('company_id', sa.BIGINT(), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'company_id', name='uq_candidate_company_follow')
    )
    op.create_index(op.f('ix_company_follows_id'), 'company_follows', ['id'], unique=False)
    op.create_table('cv_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_uploads_id'), 'cv_uploads', ['id'], unique=False)
    op.create_table('job_reports',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), nullable=False),
    sa.Column('reported_by', sa.BIGINT(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved', 'dismissed', name='jobreportstatusenum'), nullable=False),
    sa.Column('admin_action', sa.Enum('closed_job', 'no_action', name='reportadminactionenum'), nullable=True, comment='Hành động Admin đã làm khi xử lý báo cáo này'),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='Ghi chú nội bộ của Admin (tùy chọn)'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Thời điểm Admin xử lý xong báo cáo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_reports_id'), 'job_reports', ['id'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('job_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_jobs_id'), 'saved_jobs', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'review', 'interviewing', 'hired', 'rejected', 'withdrawn', 'left_company', name='applicationstatusenum'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cv_upload_id', sa.Integer(), nullable=True),
    sa.Column('cv_type', sa.Enum('profile', 'uploaded_cv', name='cvtypeenum'), nullable=False),
    sa.CheckConstraint("(cv_type = 'uploaded_cv' AND cv_upload_id IS NOT NULL) OR (cv_type = 'profile' AND cv_upload_id IS NULL)", name='ck_application_cv_type_upload_match'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cv_upload_id'], ['cv_uploads.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('session_id', sa.BIGINT(), nullable=False),
    sa.Column('sender', sa.Enum('user', 'ai', name='senderenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.BIGINT(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_logs_service_type'), 'ai_logs', ['service_type'], unique=False)
    op.create_table('ai_matching_scores',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BIGINT(), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_ai_matching_scores_id'), 'ai_matching_scores', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('interview_time', sa.DateTime(), nullable=False),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_ai_matching_scores_id'), table_name='ai_matching_scores')
    op.drop_table('ai_matching_scores')
    op.drop_index(op.f('ix_ai_logs_service_type'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_saved_jobs_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_job_reports_id'), table_name='job_reports')
    op.drop_table('job_reports')
    op.drop_index(op.f('ix_cv_uploads_id'), table_name='cv_uploads')
    op.drop_table('cv_uploads')
    op.drop_index(op.f('ix_company_follows_id'), table_name='company_follows')
    op.drop_table('company_follows')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_candidate_experiences_id'), table_name='candidate_experiences')
    op.drop_table('candidate_experiences')
    op.drop_index(op.f('ix_candidate_educations_id'), table_name='candidate_educations')
    op.drop_table('candidate_educations')
    op.drop_index(op.f('ix_candidate_certifications_id'), table_name='candidate_certifications')
    op.drop_table('candidate_certifications')
    op.drop_index(op.f('ix_user_ai_quotas_user_id'), table_name='user_ai_quotas')
    op.drop_index(op.f('ix_user_ai_quotas_id'), table_name='user_ai_quotas')
    op.drop_index(op.f('ix_user_ai_quotas_date'), table_name='user_ai_quotas')
    op.drop_table('user_ai_quotas')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_company_verifications_id'), table_name='company_verifications')
    op.drop_table('company_verifications')
    op.drop_index(op.f('ix_company_members_id'), table_name='company_members')
    op.drop_table('company_members')
    op.drop_index(op.f('ix_company_documents_id'), table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_index(op.f('ix_candidate_profiles_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_cycle'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_role_ai_quotas_role'), table_name='role_ai_quotas')
    op.drop_table('role_ai_quotas')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_ai_alert_configs_id'), table_name='ai_alert_configs')
    op.drop_table('ai_alert_configs')
    # ### end Alembic commands ###
