"""chinh lại relationship bang candidate profile

Revision ID: 5fb84dbf811d
Revises: d980bed3684d
Create Date: 2026-04-10 11:01:11.291601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb84dbf811d'
down_revision: Union[str, Sequence[str], None] = 'd980bed3684d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
