"""update

Revision ID: 649ed72d7cce
Revises: 83c594c82611
Create Date: 2026-05-12 22:48:20.502800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '649ed72d7cce'
down_revision: Union[str, Sequence[str], None] = '83c594c82611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_service_type'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ai_alert_configs_id'), table_name='ai_alert_configs')
    op.drop_table('ai_alert_configs')
    op.add_column('chat_sessions', sa.Column('candidate_id', sa.BIGINT(), nullable=False))
    op.drop_constraint(op.f('chat_sessions_application_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'candidate_profiles', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_sessions', 'application_id')
    op.alter_column('job_reports', 'admin_action',
               existing_type=postgresql.ENUM('paused_job', 'closed_job', 'warned', 'no_action', name='reportadminactionenum'),
               comment='Hành động Admin đã làm khi xử lý báo cáo này',
               existing_nullable=True)
    op.alter_column('job_reports', 'admin_note',
               existing_type=sa.TEXT(),
               comment='Ghi chú nội bộ của Admin (tùy chọn)',
               existing_nullable=True)
    op.alter_column('job_reports', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời điểm Admin xử lý xong báo cáo',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_reports', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời điểm Admin xử lý xong báo cáo',
               existing_nullable=True)
    op.alter_column('job_reports', 'admin_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ghi chú nội bộ của Admin (tùy chọn)',
               existing_nullable=True)
    op.alter_column('job_reports', 'admin_action',
               existing_type=postgresql.ENUM('paused_job', 'closed_job', 'warned', 'no_action', name='reportadminactionenum'),
               comment=None,
               existing_comment='Hành động Admin đã làm khi xử lý báo cáo này',
               existing_nullable=True)
    op.add_column('chat_sessions', sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_application_id_fkey'), 'chat_sessions', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_sessions', 'candidate_id')
    op.create_table('ai_alert_configs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_alert_configs_pkey'))
    )
    op.create_index(op.f('ix_ai_alert_configs_id'), 'ai_alert_configs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_error', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('ai_logs_application_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_logs_pkey'))
    )
    op.create_index(op.f('ix_ai_logs_service_type'), 'ai_logs', ['service_type'], unique=False)
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    # ### end Alembic commands ###
