"""add missing tables

Revision ID: 6be920c37263
Revises: 58b7c092244c
Create Date: 2026-06-28 22:51:08.678070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6be920c37263'
down_revision: Union[str, Sequence[str], None] = '58b7c092244c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('txn_ref', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=True),
    sa.Column('cycle', sa.String(length=32), nullable=False),
    sa.Column('vip_duration_days', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_subunit', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('response_code', sa.String(length=8), nullable=True),
    sa.Column('bank_code', sa.String(length=32), nullable=True),
    sa.Column('pay_date', sa.String(length=32), nullable=True),
    sa.Column('vip_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vip_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_company_id'), 'payment_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_created_by'), 'payment_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_plan_code'), 'payment_transactions', ['plan_code'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_txn_ref'), 'payment_transactions', ['txn_ref'], unique=True)
    op.create_table('ai_matching_cache',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('cv_fingerprint', sa.Text(), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', 'cv_fingerprint', name='uq_ai_matching_cache_job_candidate_fingerprint')
    )
    op.create_index(op.f('ix_ai_matching_cache_candidate_id'), 'ai_matching_cache', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ai_matching_cache_cv_fingerprint'), 'ai_matching_cache', ['cv_fingerprint'], unique=False)
    op.create_index(op.f('ix_ai_matching_cache_id'), 'ai_matching_cache', ['id'], unique=False)
    op.create_index(op.f('ix_ai_matching_cache_job_id'), 'ai_matching_cache', ['job_id'], unique=False)
    op.create_table('ai_matching_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BIGINT(), nullable=False),
    sa.Column('job_id', sa.BIGINT(), nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('cv_fingerprint', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', 'dead', name='aimatchingjobstatusenum'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_ai_matching_jobs_candidate_id'), 'ai_matching_jobs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ai_matching_jobs_cv_fingerprint'), 'ai_matching_jobs', ['cv_fingerprint'], unique=False)
    op.create_index(op.f('ix_ai_matching_jobs_id'), 'ai_matching_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_matching_jobs_job_id'), 'ai_matching_jobs', ['job_id'], unique=False)
    op.create_table('parsed_cv_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BIGINT(), nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('source_type', postgresql.ENUM('profile', 'uploaded_cv', name='cvtypeenum', create_type=False), nullable=False),
    sa.Column('parse_status', sa.Enum('pending', 'success', 'failed', name='parsestatusenum'), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text_snapshot', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_parsed_cv_data_candidate_id'), 'parsed_cv_data', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_parsed_cv_data_id'), 'parsed_cv_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_cv_data_id'), table_name='parsed_cv_data')
    op.drop_index(op.f('ix_parsed_cv_data_candidate_id'), table_name='parsed_cv_data')
    op.drop_table('parsed_cv_data')
    op.drop_index(op.f('ix_ai_matching_jobs_job_id'), table_name='ai_matching_jobs')
    op.drop_index(op.f('ix_ai_matching_jobs_id'), table_name='ai_matching_jobs')
    op.drop_index(op.f('ix_ai_matching_jobs_cv_fingerprint'), table_name='ai_matching_jobs')
    op.drop_index(op.f('ix_ai_matching_jobs_candidate_id'), table_name='ai_matching_jobs')
    op.drop_table('ai_matching_jobs')
    op.drop_index(op.f('ix_ai_matching_cache_job_id'), table_name='ai_matching_cache')
    op.drop_index(op.f('ix_ai_matching_cache_id'), table_name='ai_matching_cache')
    op.drop_index(op.f('ix_ai_matching_cache_cv_fingerprint'), table_name='ai_matching_cache')
    op.drop_index(op.f('ix_ai_matching_cache_candidate_id'), table_name='ai_matching_cache')
    op.drop_table('ai_matching_cache')
    op.drop_index(op.f('ix_payment_transactions_txn_ref'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_plan_code'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_created_by'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_company_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
