"""update

Revision ID: 778660d65970
Revises: 2bfd1e9571fa
Create Date: 2026-04-30 12:37:59.776877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778660d65970'
down_revision: Union[str, Sequence[str], None] = '2bfd1e9571fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_documents', 'status')
    # ### end Alembic commands ###
