"""rename description candidate_experience

Revision ID: 7a3dbdbd5d8e
Revises: 9e512e70f1ea
Create Date: 2026-04-06 09:38:09.220709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3dbdbd5d8e'
down_revision: Union[str, Sequence[str], None] = '9e512e70f1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_experiences', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('candidate_experiences', 'decription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_experiences', sa.Column('decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('candidate_experiences', 'description')
    # ### end Alembic commands ###
