"""chinh lại relationship bang candidate profile

Revision ID: 816e5f654f56
Revises: c73d2c09e4c2
Create Date: 2026-04-10 10:53:02.033058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816e5f654f56'
down_revision: Union[str, Sequence[str], None] = 'c73d2c09e4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
