"""chinh lại relationship bang candidate profile

Revision ID: c73d2c09e4c2
Revises: b3c36958e72b
Create Date: 2026-04-10 10:44:38.646241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73d2c09e4c2'
down_revision: Union[str, Sequence[str], None] = 'b3c36958e72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
