"""update

Revision ID: d01f1daa4f3d
Revises: e7b1338e0dfd
Create Date: 2026-04-29 11:25:54.170322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd01f1daa4f3d'
down_revision: Union[str, Sequence[str], None] = 'e7b1338e0dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'locked', name='companyverificationstatusenum'),
               nullable=True)
    op.alter_column('companies', 'is_vip',
               existing_type=postgresql.ENUM('processing', 'ready', 'failed', name='vip'),
               type_=sa.Enum('processing', 'ready', 'failed', name='vipenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'processing'::vip"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'is_vip',
               existing_type=sa.Enum('processing', 'ready', 'failed', name='vipenum'),
               type_=postgresql.ENUM('processing', 'ready', 'failed', name='vip'),
               existing_nullable=False,
               existing_server_default=sa.text("'processing'::vip"))
    op.alter_column('companies', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'locked', name='companyverificationstatusenum'),
               nullable=False)
    # ### end Alembic commands ###
