"""update

Revision ID: da22f2fb4546
Revises: bc935f5e606b
Create Date: 2026-04-10 15:35:01.361205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da22f2fb4546'
down_revision: Union[str, Sequence[str], None] = 'bc935f5e606b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('skill_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('candidate_profiles', 'skilltags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('skilltags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('candidate_profiles', 'skill_tags')
    # ### end Alembic commands ###
