"""update

Revision ID: e7b1338e0dfd
Revises: 9a0f5bd58a9d
Create Date: 2026-04-29 11:14:56.652468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b1338e0dfd'
down_revision: Union[str, Sequence[str], None] = '9a0f5bd58a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_vip', sa.Enum('processing', 'ready', 'failed', name='vip',), nullable=False,server_default='processing'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_vip')
    # ### end Alembic commands ###
