"""Add ai_quotas and update models

Revision ID: f92275fc356f
Revises: 5d3cfb60e33f
Create Date: 2026-06-14 18:18:29.489033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92275fc356f'
down_revision: Union[str, Sequence[str], None] = '5d3cfb60e33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_ai_quotas',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('daily_token_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_index(op.f('ix_role_ai_quotas_role'), 'role_ai_quotas', ['role'], unique=False)
    op.create_table('user_ai_quotas',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_ai_quota_date')
    )
    op.create_index(op.f('ix_user_ai_quotas_date'), 'user_ai_quotas', ['date'], unique=False)
    op.create_index(op.f('ix_user_ai_quotas_id'), 'user_ai_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_user_ai_quotas_user_id'), 'user_ai_quotas', ['user_id'], unique=False)
    op.add_column('ai_logs', sa.Column('user_id', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'ai_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('subscription_plans', sa.Column('daily_ai_token_limit', sa.Integer(), server_default='10000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'daily_ai_token_limit')
    op.drop_constraint(None, 'ai_logs', type_='foreignkey')
    op.drop_column('ai_logs', 'user_id')
    op.drop_index(op.f('ix_user_ai_quotas_user_id'), table_name='user_ai_quotas')
    op.drop_index(op.f('ix_user_ai_quotas_id'), table_name='user_ai_quotas')
    op.drop_index(op.f('ix_user_ai_quotas_date'), table_name='user_ai_quotas')
    op.drop_table('user_ai_quotas')
    op.drop_index(op.f('ix_role_ai_quotas_role'), table_name='role_ai_quotas')
    op.drop_table('role_ai_quotas')
    # ### end Alembic commands ###
